name: Unit tests Windows

on:
  push:
    branches:
    - develop
    - master
  pull_request:
  schedule:
  - cron: '0 0 1 * *'

jobs:
  WinVS2019:
    name: Windows VS2019
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        standard: [14, 20]
          
    steps:
    - uses: actions/checkout@v2

    - name: CMake build tests Windows
      shell: bash
      run: |
       cmake -S . -B build -DCMAKE_CXX_STANDARD=${{ matrix.standard }}
       cmake --build build --config Release
      
    - name: CMake run tests Windows
      shell: bash
      run: |
        cd build
        bin/Release/test-result
        bin/Release/test-cxx20-format
        bin/Release/test-status-code
        bin/Release/test-status-code-noexcept
        bin/Release/test-status-code-not-posix
        bin/Release/test-status-code-p0709a
