name: Unit tests Mac OS

on:
  push:
    branches:
    - develop
    - master
  pull_request:
  schedule:
  - cron: '0 0 1 * *'

jobs:
  MacOS:
    name: Mac OS
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        standard: [11, 20]
          
    steps:
    - uses: actions/checkout@v2

    - name: CMake build tests Mac OS
      shell: bash
      run: |
       mkdir build
       cd build
       cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_CXX_FLAGS="-fno-omit-frame-pointer -fsanitize=undefined" -DCMAKE_EXE_LINKER_FLAGS=-fsanitize=undefined -DCMAKE_CXX_STANDARD=${{ matrix.standard }}
       cmake --build .
      
    - name: CMake run tests Mac OS
      shell: bash
      run: |
        cd build
        bin/test-result
        bin/test-status-code
        bin/test-status-code-noexcept
        bin/test-status-code-not-posix
        bin/test-status-code-p0709a
